# SmashHit configuration

# Should criticals be enabled?
enable-criticals: true
# In 1.9, you can't achieve critical hits while sprinting.
# Enable this to use pre-1.9 behavior
old-criticals: true

# How many clicks per second are we allowing?
max-cps: 25

# How many blocks of reach can players have? // AUTOMATICALLY LIMITED TO 3 IN STEVIEBEENZ's FORK, CANNOT BE CHANGED
max-reach: 3.0

# Bridge to other PvP proteciton plugins
use-bridge:
  worldguard: true