# SmashHit configuration

# Should criticals be enabled?
enable-criticals: true
# In 1.9, you can't achieve critical hits while sprinting.
# Enable this to use pre-1.9 behavior
old-criticals: true

# How many clicks per second are we allowing?
max-cps: 25

# Bridge to other PvP proteciton plugins
# WorldGuard bridge results in instant worldguard blocks rather than delayed ones
use-bridge:
  worldguard: true

# Anticheat Compat: makes the plugin work with Anticheats
anticheat: true