name: SmashHitX
version: "0.1.0"
author: "Steviebeenz"
main: "com.frash23.smashhit.SmashHit"
depend: [  ]
softdepend: [ WorldGuard, ProtocolLib, SimplixCore ]
commands:
  smashhit:
    aliases: [ sh ]
    permission: smashhit.admin